version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - C:\Users\Oliver\Desktop\DockerLogstash\data\elasticsearch\:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch                                   # kibana will start when elasticsearch has started

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.9.1
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.monitoring.enabled: "true"
      xpack.monitoring.elasticsearch.url: "http://elasticsearch:9200"
    volumes:
      - C:\Users\Oliver\Desktop\DockerLogstash\data\logstash\:/logstash/config_dir
    ports:
      - 5017:5017
      - 5016:5016
    command: logstash -f /logstash/config_dir/logstash_beats.conf
    networks:
      - elk
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - C:\Users\Oliver\Desktop\DockerLogstash\data\nginx_logs\:/var/log/nginx/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    volumes:
      - C:\Users\Oliver\Desktop\DockerLogstash\data\nginx_logs\:/var/log/nginx
    command: >
      ./filebeat -e -c /etc/motd
      -E "filebeat.inputs=[{type:log,paths:['/var/log/nginx/access.log']}]"
      -E "output.logstash.hosts=['logstash:5016']"
    networks:
      - elk
    links:
      - logstash
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge
